In [1]:
#STEP #1: LIBRARIES IMPORT
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport  # New import
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
%pip install jupyterthemes
import sys, subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "jupyterthemes"])
from jupyterthemes import jtplot
jtplot.style(theme='monokai', context='notebook', ticks=True, grid=False)
# In terminal/Anaconda Prompt:
# jupyter nbconvert --to pdf your_notebook.ipynb
import os
print(os.getcwd())  # Shows where PDF is saved

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
C:\Users\Dell


In [2]:
df = pd.read_csv(r"C:\Users\Dell\Downloads\Adversietment\advertising.csv")
df.head(10)

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,12.0
3,151.5,41.3,58.5,16.5
4,180.8,10.8,58.4,17.9
5,8.7,48.9,75.0,7.2
6,57.5,32.8,23.5,11.8
7,120.2,19.6,11.6,13.2
8,8.6,2.1,1.0,4.8
9,199.8,2.6,21.2,15.6


In [3]:
from ydata_profiling import ProfileReport
import pandas as pd

profile = ProfileReport(df, title="Advertising Dataset Report")
profile.to_file("advertising_report.html")
print("✅ Report ready: advertising_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 47527.52it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Report ready: advertising_report.html


In [4]:
# Set style for better plots
plt.style.use('default')
sns.set_palette("husl")

print("📊 Advertising Dataset - Complete Matplotlib Profiling")
print(f"Dataset shape: {df.shape}")

# 1. CORRELATION HEATMAP (Most Important)
plt.figure(figsize=(10, 8))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0, 
            square=True, linewidths=0.5)
plt.title('Advertising Spend vs Sales - Correlation Matrix', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n🔥 Key Insights:")
print("TV-Sales correlation: {:.2f} (STRONGEST)".format(correlation_matrix.loc['Sales', 'TV']))
print("Radio-Sales: {:.2f}".format(correlation_matrix.loc['Sales', 'Radio']))
print("Newspaper-Sales: {:.2f}".format(correlation_matrix.loc['Sales', 'Newspaper']))

# 2. COMPREHENSIVE SUBPLOTS
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle('Complete Advertising Dataset Analysis', fontsize=16, fontweight='bold')

# Distribution plots
axes[0,0].hist(df['TV'], bins=20, color='red', alpha=0.7, edgecolor='black')
axes[0,0].set_title('TV Spend Distribution')
axes[0,0].set_xlabel('TV Spend ($K)')

axes[0,1].hist(df['Radio'], bins=20, color='green', alpha=0.7, edgecolor='black')
axes[0,1].set_title('Radio Spend Distribution')
axes[0,1].set_xlabel('Radio Spend ($K)')

axes[0,2].hist(df['Newspaper'], bins=20, color='blue', alpha=0.7, edgecolor='black')
axes[0,2].set_title('Newspaper Spend Distribution')
axes[0,2].set_xlabel('Newspaper Spend ($K)')

# Scatter plots vs Sales
axes[1,0].scatter(df['TV'], df['Sales'], alpha=0.6, color='red')
axes[1,0].set_title('TV vs Sales (r={:.2f})'.format(correlation_matrix.loc['Sales', 'TV']))
axes[1,0].set_xlabel('TV Spend')
axes[1,0].set_ylabel('Sales')

axes[1,1].scatter(df['Radio'], df['Sales'], alpha=0.6, color='green')
axes[1,1].set_title('Radio vs Sales (r={:.2f})'.format(correlation_matrix.loc['Sales', 'Radio']))
axes[1,1].set_xlabel('Radio Spend')
axes[1,1].set_ylabel('Sales')

axes[1,2].scatter(df['Newspaper'], df['Sales'], alpha=0.6, color='blue')
axes[1,2].set_title('Newspaper vs Sales (r={:.2f})'.format(correlation_matrix.loc['Sales', 'Newspaper']))
axes[1,2].set_xlabel('Newspaper Spend')
axes[1,2].set_ylabel('Sales')

plt.tight_layout()
plt.show()

# 3. BOX PLOTS (Outliers detection)
plt.figure(figsize=(12, 6))
df.boxplot(column=['TV', 'Radio', 'Newspaper', 'Sales'])
plt.title('Box Plots - Outlier Detection')
plt.ylabel('Values ($K)')
plt.xticks(rotation=45)
plt.show()

print("\n✅ Complete Matplotlib Profiling Complete!")
print("📈 Ready for Linear Regression modeling!")

📊 Advertising Dataset - Complete Matplotlib Profiling
Dataset shape: (200, 4)

🔥 Key Insights:
TV-Sales correlation: 0.90 (STRONGEST)
Radio-Sales: 0.35
Newspaper-Sales: 0.16


C:\Users\Dell\AppData\Local\Temp\ipykernel_16776\2358236245.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()



✅ Complete Matplotlib Profiling Complete!
📈 Ready for Linear Regression modeling!


C:\Users\Dell\AppData\Local\Temp\ipykernel_16776\2358236245.py:56: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Dell\AppData\Local\Temp\ipykernel_16776\2358236245.py:64: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [5]:
 ProfileReport(df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 10198.92it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# muliple linear regression
X_data =[['TV', 'radio']]  
y_data =['Sales']

In [7]:
X_data

[['TV', 'radio']]

In [8]:
y_data

['Sales']

In [9]:
from sklearn.model_selection import train_test_split

# Ensure proper shapes
X = df[['TV', 'Radio']]  # (200, 2) ✓
y = df['Sales'].values   # (200,)  ✓

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print("✅ All shapes correct!")

✅ All shapes correct!


In [10]:
y = df['Sales'].values

In [11]:
y

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6, 12.6,
       17.4,  9.2, 13.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 17.5,
        5.6, 20.5,  9.7, 17. , 15. , 20.9, 18.9, 10.5, 21.4, 11.9, 13.2,
       17.4, 11.9, 17.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 17.9,
        8.5, 16.1, 10.6, 23.2, 19.8,  9.7, 16.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 20.7, 14. , 16. , 11.3,
       11. , 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 17.3, 11.3, 13.6, 21.7, 20.2, 12. , 16. ,
       12.9, 16.7, 14. ,  7.3, 19.4, 22.2, 11.5, 16.9, 16.7, 20.5, 25.4,
       17.2, 16.7, 23.8, 19.8, 19.7, 20.7, 15. ,  7.2, 12. ,  5.3, 19.8,
       18.4, 21.8, 17.1, 20.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 16.6, 15.2, 19.7, 10.6,  6.6, 11.9, 24.7,  9.7,  1.6, 17.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 12.3, 10.3, 18.2, 25.4, 10.9, 10.1, 16

In [12]:
print("X shape:", X.shape)   # Should be (n, 2) or (n, 3)
print("y shape:", y.shape)   # Should be (n,) ← 1D only!

X shape: (200, 2)
y shape: (200,)


In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression
# Your current data
X = df[['TV', 'Radio']]  # (200, 2)
y = df['Sales']          # (200,)

print("X shape:", X.shape)    # (200, 2)
print("y shape:", y.shape)    # (200,)

# Reshape y to 2D
y_2d = y.values.reshape(-1, 1)  # (200, 1)
print("y_2d shape:", y_2d.shape)

# Now both X and y_2d are 2D ✓
lm_model = LinearRegression()
lm_model.fit(X, y_2d)


X shape: (200, 2)
y shape: (200,)
y_2d shape: (200, 1)


LinearRegression()

In [14]:
lm_model.coef_

array([[0.05444896, 0.10717457]])

In [15]:
lm_model.intercept_

array([4.63087946])

In [16]:
lm_model = LinearRegression()
lm_model.fit(X, y)
lm_model.score(X, y)

0.9025896186081139

In [17]:
print("Intercept:", lm_model.intercept_)
print("Slope:", lm_model.coef_[0])
r2_score = lm_model.score(X, y)
print(f"R² Score: {r2_score:.3f}")

Intercept: 4.63087946409777
Slope: 0.05444896073124317
R² Score: 0.903


In [18]:
#Adjust R SQUARE
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales ~ TV', data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Fri, 06 Mar 2026   Prob (F-statistic):           7.93e-74
Time:                        01:49:00   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
lm = smf.ols(formula='Sales ~ TV + Radio', data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Fri, 06 Mar 2026   Prob (F-statistic):          2.39e-100
Time:                        01:49:00   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
lm = smf.ols(formula='Sales ~ TV + Radio', data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Fri, 06 Mar 2026   Prob (F-statistic):          2.39e-100
Time:                        01:49:00   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""